"""initial_schema

Revision ID: 41265e8980b7
Revises: 
Create Date: 2025-04-22 20:01:33.600451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41265e8980b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('website_categories', sa.JSON(), nullable=True),
    sa.Column('estimated_monthly_traffic', sa.Integer(), nullable=True),
    sa.Column('integration_platform', sa.String(), nullable=True),
    sa.Column('preferred_task_types', sa.JSON(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishers_api_key'), 'publishers', ['api_key'], unique=True)
    op.create_index(op.f('ix_publishers_company_name'), 'publishers', ['company_name'], unique=False)
    op.create_index(op.f('ix_publishers_contact_email'), 'publishers', ['contact_email'], unique=True)
    op.create_index(op.f('ix_publishers_id'), 'publishers', ['id'], unique=False)
    op.create_index(op.f('ix_publishers_website_url'), 'publishers', ['website_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publishers_website_url'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_id'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_contact_email'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_company_name'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_api_key'), table_name='publishers')
    op.drop_table('publishers')
    # ### end Alembic commands ###
